-- BAI TAP QUAN LY GIAO VU

-- YEUCAU 1
-- Create database
CREATE DATABASE QUANLYHOCVU;	

-- Create tables
CREATE TABLE KHOA (
	MAKHOA		VARCHAR(4)		PRIMARY KEY,
	TENKHOA		VARCHAR(40),
	NGTLAP		SMALLDATETIME ,
	TRGKHOA		VARCHAR(4)
);

CREATE TABLE MONHOC (
	MAMH		VARCHAR(10)		PRIMARY KEY,
	TENMH		VARCHAR(40),
	TCLT		TINYINT,
	TCTH		TINYINT,
	MAKHOA		VARCHAR(4)
);

CREATE TABLE GIAOVIEN (
	MAGV		CHAR(4)			PRIMARY KEY,
	HOTEN		VARCHAR(40),
	HOCVI		VARCHAR(10),
	HOCHAM		VARCHAR(10),
	GIOITINH	VARCHAR(3),
	NGSINH		SMALLDATETIME,
	NGLV		SMALLDATETIME,
	HESO		NUMERIC(4,2),
	MUCLUONG	MONEY,
	MAKHOA		VARCHAR(4)
);

CREATE TABLE HOCVIEN (
	MAHV		CHAR(5)			PRIMARY KEY,
	HO			VARCHAR(40),
	TEN			VARCHAR(10),
	NGSINH		SMALLDATETIME,
	GIOITINH	VARCHAR(3),
	NOISINH		VARCHAR(40),
	MALOP		CHAR(3)
);

CREATE TABLE LOP (
	MALOP		CHAR(3)			PRIMARY KEY,
	TENLOP		VARCHAR(40),
	TRGLOP		CHAR(5),
	SISO		TINYINT,
	MAGVCN		CHAR(4)
);

CREATE TABLE GIANGDAY (
	MALOP		CHAR(3),
	MAMH		VARCHAR(10),
	MAGV		CHAR(4),
	HOCKY		TINYINT,
	NAM			SMALLINT,
	TUNGAY		SMALLDATETIME,
	DENNGAY		SMALLDATETIME

	CONSTRAINT PK_GIANGDAY	PRIMARY KEY(MALOP, MAMH)
);

CREATE TABLE KETQUATHI (
	MAHV		CHAR(5),
	MAMH		VARCHAR(10),
	LANTHI		TINYINT,		
	NGTHI		SMALLDATETIME,
	DIEM		NUMERIC(4,2),
	KQUA		VARCHAR(10)

	CONSTRAINT	PK_KQTHI	PRIMARY KEY(MAHV, MAMH, LANTHI)	
);

CREATE TABLE DIEUKIEN (
	MAMH		VARCHAR(10),
	MAMH_TRUOC	VARCHAR(10)

	CONSTRAINT	PK_DIEUKIEN	PRIMARY KEY(MAMH, MAMH_TRUOC)
);

-- Create foreign keys
ALTER TABLE MONHOC
ADD CONSTRAINT FK_MONHOC_KHOA FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA);

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GIAOVIEN_KHOA FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA);

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_TRGLOP FOREIGN KEY(TRGLOP) REFERENCES HOCVIEN(MAHV);

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_GIAOVIEN FOREIGN KEY(MAGV) REFERENCES GIAOVIEN(MAGV);

ALTER TABLE HOCVIEN
ADD CONSTRAINT FK_HOCVIEN_LOP FOREIGN KEY(MALOP) REFERENCES LOP(MALOP);

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GD_LOP FOREIGN KEY(MALOP) REFERENCES LOP(MALOP);

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GD_MONHOC FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH);

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GD_GIAOVIEN FOREIGN KEY(MAGV) REFERENCES GIAOVIEN(MAGV);

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KQ_HOCVIEN FOREIGN KEY(MAHV) REFERENCES HOCVIEN(MAHV);

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KQ_MONHOC FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH);

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DK_MAMH FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH);

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DK_MAMHTRUOC FOREIGN KEY(MAMH_TRUOC) REFERENCES MONHOC(MAMH);

-- Them GHICHU, DIEMTB, XEPLOAI cho quan he HOCVIEN
ALTER TABLE HOCVIEN
ADD GHICHU VARCHAR(50);

ALTER TABLE HOCVIEN
ADD DIEMTB NUMERIC(4,2);

ALTER TABLE HOCVIEN
ADD XEPLOAI VARCHAR(10);

-- YEUCAU 3
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CHK_GIOITINH_GV
CHECK (GIOITINH IN ('Nam', 'Nu'));

ALTER TABLE HOCVIEN
ADD CONSTRAINT CHK_GIOITINH_HV
CHECK (GIOITINH IN ('Nam', 'Nu'));

-- YEUCAU 4
ALTER TABLE KETQUATHI
ADD CONSTRAINT CHK_KQTHI
CHECK (DIEM BETWEEN 0 AND 10);

-- YEUCAU ̀5
ALTER TABLE KETQUATHI
ADD CONSTRAINT CHK_KQ
CHECK ((DIEM >= 5 AND KQUA = 'Dat') OR
		(DIEM < 5 AND KQUA = 'Khong dat'));

-- YEUCAU ̉6 ̉̉̉
ALTER TABLE KETQUATHI
ADD CONSTRAINT CHK_LANTHI
CHECK (LANTHI BETWEEN 0 AND 3);

-- YEUCAU 7
ALTER TABLE GIANGDAY
ADD CONSTRAINT CHK_HOCKY
CHECK (HOCKY BETWEEN 1 AND 3);

-- YEUCAU 8
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CHK_HOCVI_GV
CHECK (HOCVI IN ('CN', 'KS', 'ThS', 'TS', 'PTS'));