-- TÊN: NGUYỄN CHÍ NGUYÊN
-- MSSV: 24521186
-- LỚP: IT004.Q18.1

CREATE DATABASE BAITHI
GO

USE BAITHI
GO

-- Câu 1: Tạo database tên BAITHI gồm có 4 table CANGBIEN, TAU, BENCANG, CAPCANG. Tạo khóa chính, khóa ngoại cho các table đó
CREATE TABLE CANGBIEN
(
	SHCB CHAR(5) PRIMARY KEY,
	TENCANG NVARCHAR(50) NOT NULL,
	TINHTP NVARCHAR(40) NOT NULL,
	LOAICB NVARCHAR(10) NOT NULL
)

CREATE TABLE TAU
(
	SOIMO VARCHAR(10) PRIMARY KEY,
	TENTAU NVARCHAR(40) NOT NULL,
	CONGDUNG NVARCHAR(50) NOT NULL,
	TONGCS INT NOT NULL
)

CREATE TABLE BENCANG
(
	MABC VARCHAR(10) PRIMARY KEY,
	SHCB CHAR(5) NOT NULL,
	TENBC NVARCHAR(50) NOT NULL,
	SLTMAX INT NOT NULL,
	CONSTRAINT FK_BenCang_CangBien FOREIGN KEY (SHCB) REFERENCES CANGBIEN(SHCB)
)

CREATE TABLE CAPCANG
(
	SOIMO VARCHAR(10),
	MABC VARCHAR(10),
	NGCAP DATE NOT NULL,
	NGDI DATE NOT NULL
	CONSTRAINT PK_CapCang PRIMARY KEY(SOIMO, MABC),
	CONSTRAINT FK_CapCang_Tau FOREIGN KEY (SOIMO) REFERENCES TAU(SOIMO),
	CONSTRAINT FK_CapCang_BennCang FOREIGN KEY (MABC) REFERENCES BENCANG(MABC)
)

-- Câu 2: Nhập dữ liệu cho 4 table như đề bài 
INSERT INTO CANGBIEN
VALUES
('CB107', N'Cảng biển Thừa Thiên Huế', N'Thừa Thiên Huế', N'Loại 3'),
('CB305', N'Cảng biển Vũng Tàu', N'Bà Rịa - VŨng Tàu', N'Loại 1'),
('CB211', N'Cảng biển Dung Quất', N'Quãng Ngãi', N'Loại 2')

INSERT INTO TAU
VALUES
('8814225', 'APOLLO PACIFIC', N'Tàu chở khí dầu hóa lỏng', 3798),
('9371127', 'AQUAMARINE', N'Tàu chở hàng tổng hợp', 3598),
('9853955', 'PHU QUOC EXPRESS 4', N'Tàu khách', 2855)

INSERT INTO BENCANG
VALUES
('BC94', 'CB107', N'Bến cảng Chân Mây', 28),
('BC106', 'CB211', N'Bến cảng Sa Kỳ', 25),
('BC224', 'CB305', N'Bến cảng quốc tế Thị Vải', 40)

INSERT INTO CAPCANG
VALUES
('8814225', 'BC94', '2020-12-11', '2020-12-19'),
('8814225', 'BC224', '2020-12-21', '2020-12-27'),
('9371127', 'BC224', '2020-12-12', '2021-01-11')

-- Câu 3: Hiện thực ràng buộc toàn vẹn sau: Loại cảng biển chỉ có thể nhận các giá trị: Loại 1, Loại 2, Loại 3
ALTER TABLE CANGBIEN ADD CONSTRAINT CHK_CangBien_LoaiCB CHECK (LOAICB IN (N'Loại 1', N'Loại 2', N'Loại 3'))

-- Câu 4: Hiện thực ràng buộc toàn vẹn sau: Tại một thời điểm, một tàu chỉ có thể cập một bến cảng duy nhất 

-- Câu 5: Tìm các tàu cập cảng Loại 3, kết quả sắp xếp tăng dần theo tổng công suất của tàu
SELECT T.SOIMO, TENTAU, TONGCS
FROM TAU T
JOIN CAPCANG CC ON CC.SOIMO = T.SOIMO
JOIN BENCANG BC ON BC.MABC = CC.MABC
JOIN CANGBIEN CB ON CB.SHCB = BC.SHCB
WHERE CB.LOAICB = N'Loại 3'
ORDER BY T.TONGCS ASC

-- Câu 6: Tìm các cảng biển Loại 1 có số lượng tàu cập vào nhiều nhất 
SELECT CB.SHCB, TENCANG, TINHTP
FROM 
(
	SELECT CC.MABC, SHCB, COUNT(SOIMO) AS SOTAU,
	RANK() OVER
	(
		ORDER BY COUNT(SOIMO) DESC
	) AS RANKSOTAU
	FROM CAPCANG CC
	JOIN BENCANG BC ON BC.MABC = CC.MABC
	GROUP BY CC.MABC, SHCB
) AS BT
JOIN CANGBIEN CB ON CB.SHCB = BT.SHCB
WHERE LOAICB = N'Loại 1' AND RANKSOTAU = 1

-- Câu 7: Tìm các cảng biển chỉ có Tàu khách cập vào, Tàu chở hàng tổng hợp không cập vào (1đ).
SELECT CB.SHCB
FROM CANGBIEN CB
JOIN BENCANG BC ON BC.SHCB = CB.SHCB
JOIN CAPCANG CC ON CC.MABC = BC.MABC
JOIN TAU T ON T.SOIMO = CC.SOIMO
EXCEPT
SELECT CB.SHCB
FROM CANGBIEN CB
JOIN BENCANG BC ON BC.SHCB = CB.SHCB
JOIN CAPCANG CC ON CC.MABC = BC.MABC
JOIN TAU T ON T.SOIMO = CC.SOIMO
WHERE CONGDUNG LIKE N'Tàu chở%'

-- Câu 8: Tìm tàu đã cập vào tất cả các cảng biển Loại 3
SELECT *
FROM TAU T
WHERE NOT EXISTS (
	SELECT * 
	FROM CANGBIEN CB
	WHERE LOAICB = N'Loại 3'
	AND NOT EXISTS (
		SELECT * 
		FROM CAPCANG CC 
		JOIN BENCANG BC ON BC.MABC = CC.MABC
		WHERE CB.SHCB = BC.SHCB AND T.SOIMO = CC.SOIMO
	)
)